const constellations = {
    Andromeda: "Andromeda is one of the 48 constellations listed by the 2nd-century Greco-Roman astronomer Ptolemy and remains one of the 88 modern constellations.",
    Antlia: "Antlia is a constellation in the southern sky. Its name means 'pump' in Latin; it represents an air pump.",
    Apus: "Apus is a constellation in the southern sky. Its name means 'bird of paradise'.",
    Aquarius: "Aquarius is a constellation of the zodiac, situated between Capricornus and Pisces. Its name is Latin for 'water-carrier' or 'cup-carrier'.",
    Aquila: "Aquila is a constellation in the northern sky. Its name is Latin for 'eagle' and it represents the bird that carried Zeus/Jupiter's thunderbolts in Greco-Roman mythology.",
    Ara: "Ara is a southern constellation situated between Scorpius and Triangulum Australe. Its name means 'altar' in Latin.",
    Aries: "Aries is one of the constellations of the zodiac. It is located in the northern celestial hemisphere between Pisces to the west and Taurus to the east.",
    Auriga: "Auriga is one of the 48 ancient constellations first catalogued by Ptolemy. It is located north of the celestial equator.",
    Bootes: "Bootes is a constellation in the northern sky. Its name means 'herdsman' or 'plowman' in Greek.",
    Caelum: "Caelum is a faint constellation in the southern sky. Its name means 'chisel' in Latin.",
    Camelopardalis: "Camelopardalis is a large but faint constellation in the northern sky. Its name means 'giraffe' in Latin.",
    Cancer: "Cancer is one of the twelve constellations of the zodiac. Its name is Latin for crab and it is commonly represented as one.",
    CanesVenatici: "Canes Venatici is one of the 88 modern constellations. It was created by Johannes Hevelius in the 17th century and its name means 'hunting dogs' in Latin.",
    CanisMajor: "Canis Major is a constellation in the southern celestial hemisphere. Its name means 'greater dog' in Latin.",
    CanisMinor: "Canis Minor is a small constellation in the northern celestial hemisphere. Its name means 'lesser dog' in Latin.",
    Capricornus: "Capricornus is one of the constellations of the zodiac. Its name is Latin for 'horned goat' or 'goat horn' or 'having horns like a goat's'.",
    Carina: "Carina is a constellation in the southern sky. Its name means 'keel' in Latin and it represents part of Jason's ship, Argo Navis, from Greek mythology.",
    Cassiopeia: "Cassiopeia is a constellation in the northern sky, named after the vain queen Cassiopeia in Greek mythology, who boasted about her unrivaled beauty.",
    Centaurus: "Centaurus is a bright constellation in the southern sky. It contains Alpha Centauri, which is one of our nearest stellar neighbors.",
    Cepheus: "Cepheus is a constellation in the northern sky. Its name refers to Cepheus, King of Aethiopia, from Greek mythology.",
    Cetus: "Cetus is a constellation in the northern sky. Its name refers to Cetus, a sea monster from Greek mythology.",
    Chamaeleon: "Chamaeleon is a small constellation in the southern sky. It was named after chameleons because it changes its brightness like they change their colors.",
    Circinus: "Circinus is a small constellation located near Centaurus and Lupus. It was named after a drafting compass because it looks like one on star charts.",
    Columba: "Columba (Latin for dove) was created by Dutch astronomer Petrus Plancius based on observations by Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman.",
    ComaBerenices: "Coma Berenices is a constellation in the northern sky. Its name means 'Berenice's Hair' in Latin and it represents the hair of Queen Berenice II of Egypt.",
    CoronaAustralis: "Corona Australis is a constellation in the southern sky. Its name means 'southern crown' in Latin.",
    CoronaBorealis: "Corona Borealis is a small constellation in the northern sky. Its name means 'northern crown' in Latin.",
    Corvus: "Corvus is a small constellation in the southern sky. Its name means 'raven' or 'crow' in Latin.",
    Crater: "Crater is a small constellation in the southern sky. Its name means 'cup' or 'goblet' in Latin.",
    Crux: "Crux is a constellation located in the southern sky. It is one of the smallest constellations and its name means 'cross' in Latin.",
    Cygnus: "Cygnus is a constellation in the northern sky. Its name means 'swan' in Latin and it represents Zeus/Jupiter disguised as a swan to seduce Leda from Greek mythology.",
    Delphinus: "Delphinus is a small constellation in the northern sky. Its name means 'dolphin' in Latin and it represents the dolphin that saved Arion from Greek mythology.",
    Dorado: "Dorado is a constellation in the southern sky. Its name means 'dolphinfish' or 'swordfish' in Spanish.",
    Draco: "Draco is a constellation in the northern sky. Its name means 'dragon' in Latin and it represents Ladon, the dragon that guarded the golden apples from Greek mythology.",
    Equuleus: "Equuleus is one of the smallest constellations in the northern sky. Its name means 'little horse' in Latin.",
    Eridanus: "Eridanus is a constellation in the southern sky. Its name means 'the river Eridanus' in Greek mythology.",
    Fornax: "Fornax is a constellation in the southern sky. Its name means 'furnace' or 'oven' in Latin.",
    Gemini: "Gemini is one of the constellations of the zodiac. Its name is Latin for 'twins'.",
    Grus: "Grus is a constellation in the southern sky. Its name means 'crane' in Latin.",
    Hercules: "Hercules is a constellation named after Hercules, the Roman mythological hero adapted from Greek Heracles.",
    Horologium: "Horologium is a faint constellation located south of Eridanus and west of Hydrus. Its name means 'clock' or 'hourglass' in Latin.",
    Hydra: "Hydra is the largest of the modern constellations. It represents a water snake from Greek mythology and it's located south of Cancer and Leo.",
    Hydrus: "Hydrus is a small constellation located near Achernar and Octans. Its name means 'water snake' or 'male water serpent'.",
    Indus: "Indus is a constellation created by Dutch astronomer Petrus Plancius based on observations by Dutch navigators Pieter Dirkszoon Keyser and Frederick de Houtman.",
    Lacerta: "Lacerta is one of the smallest constellations and it's located between Cygnus, Andromeda, and Cassiopeia. Its name means 'lizard' or 'small lizard'.",
    Leo: "Leo is one of the constellations of the zodiac. Its name is Latin for lion and it represents Nemean Lion from Greek mythology.",
    LeoMinor: "Leo Minor is a small constellation located between Leo and Ursa Major. Its name means 'small lion'.",
    Lepus: "Lepus is a small constellation located south of Orion. Its name means hare or rabbit in Latin.",
    Libra: "Libra is one of the constellations of the zodiac. Its name means scales or balance beam in Latin.",
    Lupus: "Lupus is a constellation located south of Centaurus. Its name means wolf or wolf cub in Latin.",
    Lynx: "Lynx is a faint constellation located between Ursa Major and Auriga. It was named after Lynx, a wild cat.",
    Lyra: "Lyra is a constellation in the northern sky. Its name means 'lyre' in Latin and it represents the lyre of Orpheus from Greek mythology.",
    Mensa: "Mensa is a constellation in the southern sky. Its name means 'table' in Latin.",
    Microscopium: "Microscopium is a faint constellation located south of Sagittarius. Its name means 'microscope' in Latin.",
    Monoceros: "Monoceros is a faint constellation located near Orion and Canis Major. Its name means 'unicorn' in Greek mythology.",
    Musca: "Musca is a small constellation located near Crux and Centaurus. Its name means 'fly' in Latin.",
    Norma: "Norma is a small constellation located between Scorpius and Centaurus. Its name means 'carpenter's square' in Latin.",
    Octans: "Octans is a faint constellation located south of Tucana and west of Hydrus. Its name means 'octant' or 'sextant' in Latin.",
    Ophiuchus: "Ophiuchus is a large constellation located near Scorpius. Its name means 'serpent-bearer' in Greek mythology.",
    Orion: "Orion is one of the most recognizable constellations in the sky. It represents Orion, a hunter from Greek mythology.",
    Pavo: "Pavo is a constellation in the southern sky. Its name means 'peacock' in Latin.",
    Pegasus: "Pegasus is a constellation in the northern sky. Its name means 'winged horse' in Greek mythology.",
    Perseus: "Perseus is a constellation named after Perseus, a hero from Greek mythology who killed Medusa.",
    Phoenix: "Phoenix is a constellation in the southern sky. Its name means 'phoenix' in Greek mythology.",
    Pictor: "Pictor is a faint constellation located south of Caelum and west of Carina. Its name means 'painter' or 'easel' in Latin.",
    Pisces: "Pisces is one of the constellations of the zodiac. Its name means fish in Latin and it represents Aphrodite and Eros disguised as fish to escape Typhon from Greek mythology.",
    PiscisAustrinus: "Piscis Austrinus is a faint constellation located near Aquarius and Capricornus. Its name means 'southern fish' in Latin.",
    Puppis: "Puppis is a large constellation located near Canis Major and Carina. Its name means 'poop deck' or 'stern' in Latin.",
    Pyxis: "Pyxis is a small constellation located near Hydra and Puppis. Its name means 'compass' or 'mariner's compass' in Latin.",
    Reticulum: "Reticulum is a small constellation located south of Horologium and Hydrus. Its name means 'reticle' or 'crosshairs' in Latin.",
    Sagitta: "Sagitta is a small constellation located between Cygnus and Aquila. Its name means arrow in Latin.",
    Sagittarius: "Sagittarius is one of the constellations of the zodiac. Its name means archer or bowman in Latin and it represents Chiron, the centaur from Greek mythology who taught archery to Achilles.",
    Scorpius: "Scorpius is one of the constellations of the zodiac. Its name means scorpion in Latin and it represents Scorpius, the scorpion that killed Orion from Greek mythology.",
    Sculptor: "Sculptor is a faint constellation located in the southern sky. It was named after the sculptor's tools.",
    Scutum: "Scutum is a small constellation located in the southern sky. Its name means 'shield' in Latin.",
    Serpens: "Serpens is a constellation located between Ophiuchus and Scorpius. Its name means 'serpent' in Latin.",
    Taurus: "Taurus is one of the constellations of the zodiac. Its name means 'bull' in Latin and it represents Zeus disguised as a bull from Greek mythology.",
    Telescopium: "Telescopium is a small constellation located in the southern sky. Its name means 'telescope' in Latin.",
    Triangulum: "Triangulum is a small constellation located between Andromeda and Aries. Its name means 'triangle' in Latin.",
    TriangulumAustrale: "Triangulum Australe is a small constellation located in the southern sky. Its name means 'southern triangle' in Latin.",
    Tucana: "Tucana is a small constellation located in the southern sky. Its name means 'toucan' in Portuguese.",
    UrsaMajor: "Ursa Major is one of the most recognizable constellations in the sky. Its name means 'great bear' in Latin and it represents Callisto from Greek mythology.",
    UrsaMinor: "Ursa Minor is a small constellation located near Ursa Major. Its name means 'little bear' in Latin and it represents Arcas from Greek mythology.",
    Vela: "Vela is a large constellation located near Carina and Puppis. Its name means 'sails' in Latin.",
    Virgo: "Virgo is one of the constellations of the zodiac. Its name means 'virgin' in Latin and it represents Persephone from Greek mythology.",
    Volans: "Volans is a faint constellation located in the southern sky. Its name means 'flying fish' in Latin.",
    Vulpecula: "Vulpecula is a faint constellation located near Cygnus and Lyra. Its name means 'little fox' in Latin."

}   